import type { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./i18n/request.ts');

/**
 * IqraQuest website — build configuration.
 *
 * The site is a **fully static export**: `next build` writes plain
 * HTML/CSS/JS to `out/`, which GitHub Pages serves directly. That
 * choice has consequences the rest of the codebase is written around:
 *
 * - No middleware. Locale routing is resolved at build time by
 *   `generateStaticParams`, and French is emitted un-prefixed at the
 *   root so `https://iqraquest.org/` is the canonical homepage.
 * - No route handlers. The contact form posts to a configurable
 *   endpoint and degrades to a pre-filled `mailto:` when none is set.
 * - No `headers()` / `redirects()`. GitHub Pages serves a fixed header
 *   set and cannot be given custom ones; the security headers a Node
 *   host would send are documented in DEPLOYMENT.md, and the subset
 *   that a document can declare for itself is emitted as
 *   `<meta http-equiv>` by the root layout. The apex/www redirect is
 *   handled by GitHub Pages itself once both DNS records exist.
 * - No image optimizer. Every size the site needs is pre-generated by
 *   `scripts/prepare-assets.mjs` and committed, so `next/image` runs
 *   unoptimized over artwork that is already the right size and format.
 *
 * Linting is a separate, blocking CI step (`npm run lint`) rather than
 * part of the build.
 */
const nextConfig: NextConfig = {
  output: 'export',
  reactStrictMode: true,
  poweredByHeader: false,

  // GitHub Pages resolves `/game/` to `/game/index.html`. Emitting the
  // trailing-slash form means every internal link matches the file that
  // actually exists, with no server-side rewrite to lean on.
  trailingSlash: true,

  images: {
    // The static host has no optimizer endpoint. Artwork is pre-encoded
    // to AVIF/WebP at the exact widths the layouts request.
    unoptimized: true,
  },

};

export default withNextIntl(nextConfig);
