/* AUTOGENERATED by scripts/gen-routes.mjs — do not edit by hand.
   Edit the page implementation in components/pages/, or the PAGES
   table in the generator, then re-run `npm run routes`. */
import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { HomePage } from '@/components/pages';
import { buildMetadata, homeStructuredData } from '@/lib/seo';
import { defaultLocale, locales, type Locale } from '@/i18n/routing';

export function generateStaticParams() {
  return locales
    .filter((locale) => locale !== defaultLocale)
    .map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const typed = locale as Locale;
  const tm = await getTranslations({ locale: typed, namespace: 'meta' });

  return buildMetadata({
    locale: typed,
    path: '',
    title: tm('siteTitle'),
    description: tm('siteDescription'),
    ogImageAlt: tm('ogAlt'),
  });
}

export default async function Page({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const typed = locale as Locale;
  setRequestLocale(typed);

  const tm = await getTranslations({ locale: typed, namespace: 'meta' });

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: homeStructuredData(typed, tm('siteDescription')),
        }}
      />
      <HomePage />
    </>
  );
}
