/* AUTOGENERATED by scripts/gen-routes.mjs — do not edit by hand.
   Edit the page implementation in components/pages/, or the PAGES
   table in the generator, then re-run `npm run routes`. */
import type { Metadata } from 'next';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import { KnowledgePage } from '@/components/pages';
import { buildMetadata, breadcrumbStructuredData } from '@/lib/seo';
import { defaultLocale } from '@/i18n/routing';
import { siteConfig } from '@/config/site.config';

export async function generateMetadata(): Promise<Metadata> {
  const typed = defaultLocale;
  const t = await getTranslations({ locale: typed, namespace: 'knowledgePage' });
  const tm = await getTranslations({ locale: typed, namespace: 'meta' });

  return buildMetadata({
    locale: typed,
    path: 'knowledge',
    title: `${t('title')} — ${siteConfig.siteName}`,
    description: t('metaDescription'),
    ogImageAlt: tm('ogAlt'),
  });
}

export default async function Page() {
  const typed = defaultLocale;
  setRequestLocale(typed);

  const t = await getTranslations({ locale: typed, namespace: 'knowledgePage' });

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: breadcrumbStructuredData(typed, siteConfig.siteName, {
            label: t('title'),
            path: 'knowledge',
          }),
        }}
      />
      <KnowledgePage />
    </>
  );
}
