#!/usr/bin/env node
/**
 * Generates the two route trees.
 *
 * The site serves French un-prefixed (`/game`) and every other language
 * prefixed (`/en/game`). With a static export there is no middleware to
 * resolve that at request time, so both trees have to exist as files.
 *
 * Writing them by hand would mean maintaining eighteen near-identical
 * page files and hoping they stay in step. Instead each page's real
 * implementation lives in `components/pages/`, and this script emits
 * the thin route files that mount it. Run it after adding a route:
 *
 *   npm run routes
 *
 * The output is committed — the build never depends on this script.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * Every page of the site.
 *
 * - `component`  export from `components/pages`
 * - `messages`   namespace holding its copy
 * - `descKey`    key inside that namespace used as the meta description
 * - `faqKey`     present when the page should emit an FAQPage graph
 */
const PAGES = [
  { path: '', component: 'HomePage', messages: 'home', home: true },
  {
    path: 'game',
    component: 'GamePage',
    messages: 'gamePage',
    descKey: 'metaDescription',
  },
  {
    path: 'how-to-play',
    component: 'HowToPlayPage',
    messages: 'howToPlayPage',
    descKey: 'metaDescription',
    faqKey: 'faq',
  },
  {
    path: 'about',
    component: 'AboutPage',
    messages: 'aboutPage',
    descKey: 'metaDescription',
  },
  {
    path: 'support',
    component: 'SupportPage',
    messages: 'supportPage',
    descKey: 'metaDescription',
    faqKey: 'faq',
  },
  {
    path: 'contact',
    component: 'ContactPage',
    messages: 'contactPage',
    descKey: 'metaDescription',
  },
  {
    path: 'privacy',
    component: 'PrivacyPage',
    messages: 'privacyPage',
    descKey: 'metaDescription',
  },
  {
    path: 'terms',
    component: 'TermsPage',
    messages: 'termsPage',
    descKey: 'metaDescription',
  },
  {
    path: 'intellectual-property',
    component: 'IntellectualPropertyPage',
    messages: 'ipPage',
    descKey: 'metaDescription',
  },
];

const HEADER = `/* AUTOGENERATED by scripts/gen-routes.mjs — do not edit by hand.
   Edit the page implementation in components/pages/, or the PAGES
   table in the generator, then re-run \`npm run routes\`. */
`;

function routeFile(page, prefixed) {
  const seoImports = ['buildMetadata'];
  seoImports.push(page.home ? 'homeStructuredData' : 'breadcrumbStructuredData');
  if (page.faqKey) seoImports.push('faqStructuredData');

  const routingImports = prefixed
    ? `import { defaultLocale, locales, type Locale } from '@/i18n/routing';`
    : `import { defaultLocale } from '@/i18n/routing';`;

  const imports = [
    `import type { Metadata } from 'next';`,
    `import { getTranslations, setRequestLocale } from 'next-intl/server';`,
    `import { ${page.component} } from '@/components/pages';`,
    `import { ${seoImports.join(', ')} } from '@/lib/seo';`,
    routingImports,
  ];
  if (!page.home) imports.push(`import { siteConfig } from '@/config/site.config';`);

  const signature = prefixed
    ? `{\n  params,\n}: {\n  params: Promise<{ locale: string }>;\n}`
    : '';

  const resolveLocale = prefixed
    ? `  const { locale } = await params;\n  const typed = locale as Locale;`
    : `  const typed = defaultLocale;`;

  const staticParams = prefixed
    ? `
export function generateStaticParams() {
  return locales
    .filter((locale) => locale !== defaultLocale)
    .map((locale) => ({ locale }));
}
`
    : '';

  // The homepage owns the brand title; every other page appends it.
  const title = page.home
    ? `tm('siteTitle')`
    : `\`\${t('title')} — \${siteConfig.siteName}\``;
  const description = page.home
    ? `tm('siteDescription')`
    : `t('${page.descKey}')`;

  const pageBodyTranslations = page.home
    ? `
  const tm = await getTranslations({ locale: typed, namespace: 'meta' });
`
    : `
  const t = await getTranslations({ locale: typed, namespace: '${page.messages}' });
`;

  const graphs = [];
  graphs.push(
    page.home
      ? `          __html: homeStructuredData(typed, tm('siteDescription')),`
      : `          __html: breadcrumbStructuredData(typed, siteConfig.siteName, {
            label: t('title'),
            path: '${page.path}',
          }),`,
  );

  const scripts = graphs
    .map(
      (body) => `      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
${body}
        }}
      />`,
    )
    .join('\n');

  const faqScript = page.faqKey
    ? `
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: faqStructuredData(
            t.raw('${page.faqKey}') as { question: string; answer: string }[],
          ),
        }}
      />`
    : '';

  // The homepage titles itself from `meta`; every other page reads its
  // own namespace. Declaring an unused translator would fail lint.
  const metadataTranslations = page.home
    ? `  const tm = await getTranslations({ locale: typed, namespace: 'meta' });`
    : `  const t = await getTranslations({ locale: typed, namespace: '${page.messages}' });
  const tm = await getTranslations({ locale: typed, namespace: 'meta' });`;

  return `${HEADER}${imports.join('\n')}
${staticParams}
export async function generateMetadata(${signature}): Promise<Metadata> {
${resolveLocale}
${metadataTranslations}

  return buildMetadata({
    locale: typed,
    path: '${page.path}',
    title: ${title},
    description: ${description},
    ogImageAlt: tm('ogAlt'),
  });
}

export default async function Page(${signature}) {
${resolveLocale}
  setRequestLocale(typed);
${pageBodyTranslations}
  return (
    <>
${scripts}${faqScript}
      <${page.component} />
    </>
  );
}
`;
}

async function main() {
  let written = 0;

  for (const page of PAGES) {
    for (const prefixed of [false, true]) {
      const base = prefixed ? 'app/(intl)/[locale]' : 'app/(default)';
      const dir = page.path ? path.join(base, page.path) : base;
      await mkdir(dir, { recursive: true });
      await writeFile(
        path.join(dir, 'page.tsx'),
        routeFile(page, prefixed),
        'utf8',
      );
      written += 1;
    }
  }

  console.log(`${written} route files written.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
