#!/usr/bin/env python3
"""
Traces the word اقرأ ("Iqra" — "Read") into a single SVG path.

The outlines come from the application's own Noto Naskh Arabic face and
are shaped with HarfBuzz so the letters take their proper joined forms.
Shipping the word as a path rather than as text means a French or
English page can carry the brand's Arabic word without fetching the
Arabic font for four letters, and it stays crisp at any size.

    python3 scripts/trace-iqra-mark.py

Writes components/brand/IqraMark.tsx. Requires `fonttools` and
`uharfbuzz` (pip). Re-run only if the face or the word changes.
"""
import os
import sys

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

APP_DIR = os.environ.get("IQRAQUEST_APP_DIR", os.path.abspath("../upasco/iqraquest"))
FONT = os.path.join(APP_DIR, "assets/fonts/NotoNaskhArabic-Regular.ttf")
WORD = "اقرأ"
OUT = os.path.abspath("components/brand/IqraMark.tsx")


def shape(word):
    blob = hb.Blob.from_file_path(FONT)
    face = hb.Face(blob)
    font = hb.Font(face)
    buf = hb.Buffer()
    buf.add_str(word)
    buf.guess_segment_properties()
    hb.shape(font, buf)
    return face.upem, list(zip(buf.glyph_infos, buf.glyph_positions))


def draw(glyphset, order, run, pen_factory):
    """Lays the shaped run out along x, Y flipped so the path is SVG-up."""
    x = 0
    pen = pen_factory()
    for info, pos in run:
        name = order[info.codepoint]
        tp = TransformPen(pen, (1, 0, 0, -1, x + pos.x_offset, -pos.y_offset))
        glyphset[name].draw(tp)
        x += pos.x_advance
    return pen


def main():
    if not os.path.exists(FONT):
        sys.exit(f"font not found: {FONT}\nSet IQRAQUEST_APP_DIR to a checkout of the app.")

    upem, run = shape(WORD)
    tt = TTFont(FONT)
    glyphset = tt.getGlyphSet()
    order = tt.getGlyphOrder()

    path = draw(glyphset, order, run, lambda: SVGPathPen(glyphset)).getCommands()
    xmin, ymin, xmax, ymax = draw(glyphset, order, run, lambda: BoundsPen(glyphset)).bounds

    pad = upem * 0.04
    view_box = f"{xmin - pad:.0f} {ymin - pad:.0f} {xmax - xmin + 2 * pad:.0f} {ymax - ymin + 2 * pad:.0f}"
    aspect = (ymax - ymin + 2 * pad) / (xmax - xmin + 2 * pad)

    tsx = f'''/**
 * The word اقرأ — "Iqra", "Read" — as a single vector path.
 *
 * Traced from the application's own Noto Naskh Arabic face and shaped
 * with HarfBuzz so the letters take their proper joined forms. Shipping
 * it as a path rather than as text means a French or English page can
 * carry the brand's Arabic word without fetching the 90 kB Arabic font
 * for four letters, and it stays crisp at any size.
 *
 * It is a word, drawn as type. It depicts nothing.
 *
 * Generated by scripts/trace-iqra-mark.py — do not edit by hand.
 */
export function IqraMark({{
  className,
  title,
}}: {{
  className?: string;
  /** Accessible name. Omit to mark the glyph decorative. */
  title?: string;
}}) {{
  return (
    <svg
      viewBox="{view_box}"
      className={{className}}
      role={{title ? 'img' : undefined}}
      aria-hidden={{title ? undefined : true}}
      focusable="false"
    >
      {{title && <title>{{title}}</title>}}
      <path fill="currentColor" d="{path}" />
    </svg>
  );
}}

/** Height / width of the viewBox, for reserving space before paint. */
export const IQRA_MARK_ASPECT = {aspect:.4f};
'''
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(tsx)
    print(f"{os.path.relpath(OUT)} written — viewBox {view_box}, {len(run)} glyphs")


if __name__ == "__main__":
    main()
